<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
    
<%-- 머리글 포함(파라미터(title)가 있으므로 동적 페이지 포함) --%>
<jsp:include page="template/header.jsp" />
    
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAINMAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAINMAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAINMAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAINMAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>
	MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN<br/>

<%@ include file="template/footer.jsp" %>